### ISSUE TITLE
[SOLVED]Sabotage Type

### ISSUE THREAD

**Issue by NebzHB** [KhaosT/HAP-NodeJS#463] opened 2017-06-26 07:13 UTC
Hello All,

i've seen that the HomeKit Fibaro Motion Sensor (the Eye) have a sabotage service... do you know which Characteristic it uses ?

BR's

**Comment by thermogl** [comment] 2017-07-02 21:05
There is a "Status Tampered" characteristic listed in HomeKitTypes.js with NOT_TAMPERED and TAMPERED as the possible values

**Comment by NebzHB** [comment] 2017-07-03 07:50
Thank you, that was not obvious for non-english native ;)

**Comment by rodorgas** [comment] 2017-08-28 01:48
You should close the issue (there's a button called `Close issue`), not change the title.

**Closed** 2017-08-28 02:03 UTC

**Comment by snowdd1** [comment] 2017-08-29 14:04
somewhat off-topic, but I like the change-title theme, **additionally** to closing the issue.
That's why: Closing means the issue is not worked on any more - can be solved, or could be a duplicate, or the owner lost interest, abandoned/incomplete etc.

The [solved] title immediately shows to anyone having the same issue: Here it is, and the solution is here, too.
That would require there were standard tags for the other states as well, or the repo owner would give tags, which is a heck of work in public repos as HAP and HOMEBRIDGE. So it just might be that: a good idea... [abandoned]...
